---
title             : "Supplementary Tables: Cognitive Load and Moral Dumbfounding"
shorttitle        : "Cognitive Load and Moral Dumbfounding"
author:
  - name          : "Blinded"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Blinded"
    email         : "Blinded"
  - name          : "Blinded"
    affiliation   : "2"
  - name          : "Blinded"
    affiliation   : "1"
  - name          : "Blinded"
    affiliation   : "1"
affiliation:
  - id            : "1"
    institution   : "Blinded"
  - id            : "2"
    institution   : "Blinded"
author_note: >
  n/a
abstract: >
  n/a
keywords          : "keywords"
wordcount         : "TBC"
bibliography: "../resources/bib/My Library.bib"
csl: "../resources/bib/apa6.csl"
figsintext        : no
floatsintext      : yes
figurelist        : yes
tablelist         : yes
footnotelist      : no
lineno            : no
toc               : false
lang              : "en-US"
documentclass     : "apa7"
output:
  papaja::apa6_pdf
header-includes:
- \usepackage{float}
editor_options: 
  chunk_output_type: console
---

# Supplementary Tables

Below are additional tables:

\newpage

```{r}
#knitr::opts_chunk$set(fig.pos = "!p", out.extra = "")
```


```{r tabload_libraries_cogload, include=FALSE, echo=FALSE}
rm(list = ls())
library(citr)
#install.packages("sjstats")
library(plyr)
library(foreign)
library(car)
library(desnum)
library(ggplot2)
library(extrafont)
#devtools::install_github("crsh/papaja")
library(papaja)
#library("dplyr")
library("afex")
library("tibble")
library(scales)
#install.packages("metap")
library(metap)
library(pwr)
library(lsr)
#install.packages("sjstats")
library(sjstats)
library(DescTools)
#inatall.packages("ggstatsplot")
#library(ggstatsplot)
library(VGAM)
library(nnet)
library(mlogit)
library(reshape2)
#install.packages("powerMediation")
library("powerMediation")


#source("load_all_data.R")

#devtools::install_github("benmarwick/wordcountaddin")
#library(wordcountaddin)
#wordcountaddin::text_stats("cogload_1to5_25Sept19.Rmd")
#getwd()
```


```{r tabsetup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
# knitr::opts_chunk$set(eval = TRUE, echo = TRUE)
#knitr::opts_chunk$set(include = FALSE)
```



```{r tabload data set Study 1}

rm(list = ls())

load("../loaded_data/one.RData")
df3 <- study_1

df4 <- df3[which(df3$condition=="cog_load"),]
df5 <- df3[which(df3$condition=="control"),]


```


```{r tabs1change in judgement}

# create variables for reporting t.tests
t <- t.test(df3$InJu1,df3$InJu2, paired = TRUE)

#chisquare test function

custom_chi <- function(x,y){
  a <- length(x)
  b <- length(y)
  c <- rep(1, a)
  d <- rep(2, b)
  e <- c(c,d)
  f <- c(x, y)
  
  g <- data.frame(e,f)
  h <- table(g$e,g$f)
  suppressWarnings(chisq.test(h))
}

c <- suppressWarnings(custom_chi(df3$InJu1,df3$InJu2))

changed_num <- function(x, judgement_1, judgement_2){
  b <- b <- x[which(x$Ju1_bin==judgement_1 & x$Ju2_bin==judgement_2),]
  length(b$Ju1_bin)
  
}

tot_changed_num <- function(x, query){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  if(query == "table")
    print(c)
  if(query == "total") print(length(c$initial_judgement))}


tot_changed_table <- function(x){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  }

change_table <- tot_changed_table(df3)
change_table <- table(change_table)
change_table <- as.data.frame(change_table)
change_table <- change_table[which(change_table$Freq!=0),]
change_table <- change_table[order(change_table$Initial.Judgment, change_table$Revised.Judgment), ]
colnames(change_table) <- c("Initial Judgment","Revised Judgment", "Total Changed")
#order(change_table$Initial.Judgment)
```



```{r tabS1change,results = 'asis', include=TRUE}


apa_table(
   change_table
   , align = c("c", "c")
   , caption = "Study 1 – Changes in Jugment"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}

c <- chisq.test(table(df3$InCS,df3$condition))
w <- sqrt(c[]$statistic/length(df3$gender))
pw <- pwr.chisq.test(w=w,N=length(df3$InCS),df=(3-1),sig.level = .05)

```



```{r}

df3$InCS <- df3$InCS

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")
  
makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)

df3 <- study_1


```


```{r tabS1tab1dumb1all,results = 'asis', include=TRUE}


apa_table(
   test
   , align = c("l", "c", "c", "c", "c")
   , caption = "Study 1 – Response to the critical slide depending on cognitive load"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```



```{r tabpreptableS1}
c <- chisq.test(table(df3$InCS,df3$condition))
rownames(rbind(c$observed,c$expected,c$stdres))



ps <- function(y){
  if(as.numeric(sqrt( y*y) ) >3.3) print(paste0(y,"**"), quote = FALSE)
  else if(as.numeric(sqrt( y*y) ) >1.96) print(paste0(y,"*"), quote = FALSE)
  else print(y)}


x <- c$stdres
x <- round(x, digits = 2)

lapply(x, ps)

#c$stdres <- round(c$stdres,digits=3)
#c$stdres <- ps(c$stdres)

ps(x[1])
ps(x[2])
ps(x[3])

x <- `colnames<-`(
  cbind.data.frame(c(ps(x[1]),ps(x[2]),ps(x[3])),
                   c(ps(x[4]),ps(x[5]),ps(x[6]))),
  c("cog_load","control")
)

rownames(x) <- row.names(c$observed)  

y <- rbind(round(c$observed), round(c$expected, digits = 2))

c(c$stdres[1])


res <- cbind(c("Observed count","","","Expected count","","","Standardised residuals","",""),
      c("Nothing Wrong","Dumbfounded","Reasons",
        "Nothing Wrong","Dumbfounded","Reasons",
        "Nothing Wrong","Dumbfounded","Reasons"),
      rbind(y,x)
      
      )

row.names(res) <- NULL
colnames(res) <- c("","","Cognitive Load","Control")




```

```{r tabS1res,results = 'asis', include=FALSE}


apa_table(
   res
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 1 – Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on cognitive load"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   , note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r tabch5cognitive load manipulationS1, include=FALSE}


df_a <- df3[which(df3$cog_right=="right"&df3$cog_M_ch_bin=="easy"),]
table(df_a$InCS)
numbers2words(sum(df_a$InCS=="There is nothing wrong."))
numbers2words(sum(df_a$InCS=="It's wrong but I can't think of a reason."))
numbers2words(sum(df_a$InCS=="It's wrong and I can provide a valid reason."))


df4 <- df3[which(df3$condition=="cog_load"),]
df5 <- df3[which(df3$condition=="control"),]
c <- chisq.test(table(df3$InCS,df3$condition))
#table(df3$InCS,df3$condition)

descriptives(df4$cog_number_right)
table(df4$cog_number_right)
table(df4$cog_M_ch_bin)
table(df4$cog_M_ch_bin,df4$cog_number_right)
numbers2words(min(df4$cog_number_right))

cbind(
  df4$cog_right,
  df4$cog_number_right
)
sum(df4$cog_number_right==0)

#c
```


```{r tabch5cognitive load and engagement with the taskS1, include=FALSE}

#tapply(df3$InCf1, df3$condition, descriptives)
#t.test(df3$InCf1~df3$condition)
t <- t.test(InJu1~condition, data=df3)
t1 <- t.test(InCf1~condition, data=df3)

d <- cohensD(InJu1~condition, data=df3)
d1 <- cohensD(InCf1~condition, data=df3)
```



```{r tablogit1b}

df3$InCS <- relevel(df3$InCS, ref = 2)

df3a <- mlogit.data(df3, choice = "InCS", shape = "wide")
InCSModel<-mlogit(InCS ~ 1 | condition+NFC, data = df3a, reflevel = "It's wrong and I can provide a valid reason."
                  )

summary_InCS_model <- summary(InCSModel)
summary_InCS_model$lratio$parameter
summary_InCS_model$lratio$statistic
summary_InCS_model$lratio$p.value

InCSModel$coefficients[3]
InCSModel$coefficients[4]

cox <- PseudoR2(multinom(InCS~condition+NFC,df3), "all")

cox[3]
cox[4]
#PseudoR2(x, "all")
#summary_InCS_model


wald1 <- 
  summary_InCS_model$CoefTable[3]^2 /
  summary_InCS_model$CoefTable[7]^2

wald2 <- 
  summary_InCS_model$CoefTable[4]^2 /
  summary_InCS_model$CoefTable[8]^2


summary_InCS_model
summary_InCS_model$coefficients[3]
data.frame(exp(InCSModel$coefficients))

exp(InCSModel$coefficients)[3]


a <- exp(confint(InCSModel))
c(a[3],a[7])

residuals(InCSModel)
fitted(InCSModel, outcome = F)

c <- summary_InCS_model$lratio$statistic
w <- sqrt(c/length(df3$gender))
pw <- pwr.chisq.test(w=w,N=length(df3$InCS),df=(2),sig.level = .05)

pw$power

revised_PseudoR2s <- function(LogModel) {
  dev <- LogModel$deviance
  nullDev <- LogModel$null.deviance
  modelN <- length(LogModel$fitted.values)
  R.l <- 1 - dev / nullDev
  R.cs <- 1- exp ( -(nullDev - dev) / modelN)
  R.n <- R.cs / ( 1 - ( exp (-(nullDev / modelN))))
  
  all <- list(hosmer_and_lemeshow = as.numeric(R.l), mcfadden = NA, cox_and_snell = as.numeric(R.cs), nagelkerke = as.numeric(R.n))
  all
}

logits_rsquared <- glm(InCS~NFC,df3, family = binomial(link = "logit"))
cox <- revised_PseudoR2s(logits_rsquared)

```

```{r tablogit1}

df3$InCS <- relevel(df3$InCS, ref = 2)

df3a <- mlogit.data(df3, choice = "InCS", shape = "wide")
InCSModel<-mlogit(InCS ~ 1 | NFC, data = df3a, reflevel = "It's wrong and I can provide a valid reason.")

summary_InCS_model <- summary(InCSModel)
summary_InCS_model$lratio$parameter
summary_InCS_model$lratio$statistic
summary_InCS_model$lratio$p.value

InCSModel$coefficients[3]
InCSModel$coefficients[4]

cox <- PseudoR2(multinom(InCS~NFC,df3), "all")

cox[3]
cox[4]
#PseudoR2(x, "all")
#summary_InCS_model


wald1 <- 
  summary_InCS_model$CoefTable[3]^2 /
  summary_InCS_model$CoefTable[7]^2

wald2 <- 
  summary_InCS_model$CoefTable[4]^2 /
  summary_InCS_model$CoefTable[8]^2


summary_InCS_model
summary_InCS_model$coefficients[3]
data.frame(exp(InCSModel$coefficients))

exp(InCSModel$coefficients)[3]


a <- exp(confint(InCSModel))
c(a[3],a[7])

residuals(InCSModel)
fitted(InCSModel, outcome = F)

c <- summary_InCS_model$lratio$statistic
w <- sqrt(c/length(df3$gender))
pw <- pwr.chisq.test(w=w,N=length(df3$InCS),df=(2),sig.level = .05)

pw$power

revised_PseudoR2s <- function(LogModel) {
  dev <- LogModel$deviance
  nullDev <- LogModel$null.deviance
  modelN <- length(LogModel$fitted.values)
  R.l <- 1 - dev / nullDev
  R.cs <- 1- exp ( -(nullDev - dev) / modelN)
  R.n <- R.cs / ( 1 - ( exp (-(nullDev / modelN))))
  
  all <- list(hosmer_and_lemeshow = as.numeric(R.l), mcfadden = NA, cox_and_snell = as.numeric(R.cs), nagelkerke = as.numeric(R.n))
  all
}

logits_rsquared <- glm(InCS~NFC,df3, family = binomial(link = "logit"))
cox <- revised_PseudoR2s(logits_rsquared)

```

```{r tabfullcombinedtestlogit, include=FALSE}
# taken from https://stats.idre.ucla.edu/r/dae/multinomial-logistic-regression/
#ml$prog2 <- relevel(ml$prog, ref = "academic")
df3 <- df3[which(is.na(df3$NFC)==FALSE),]
df3$InCS <- relevel(df3$InCS, ref = 3)

test <- multinom(InCS ~ condition + NFC, data = df3)
summary(test)
z <- summary(test)$coefficients/summary(test)$standard.errors
z
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p

exp(coef(test))
head(pp <- fitted(test))

## different order from here, be careful

dses <- data.frame(condition = c("cog_load", "control" ), NFC = mean(df3$NFC))
predict(test, newdata = dses, "probs")

dwrite <- data.frame(condition = rep(c("cog_load", "control" ), each = 41), NFC = rep(c(30:70),
    2))

## store the predicted probabilities for each value of ses and write
pp.write <- cbind(dwrite, predict(test, newdata = dwrite, type = "probs", se = TRUE))

## calculate the mean probabilities within each level of ses
by(pp.write[, 3:5], pp.write$condition, colMeans)

lpp <- melt(pp.write, id.vars = c("condition", "NFC"), value.name = "probability")
head(lpp)

ggplot(lpp, aes(x = NFC, y = probability, colour = variable)) + geom_line() + facet_grid(. ~ condition, scales = "free")

```


\newpage

```{r tabprepplottinglogit1}

df3 <- df3[which(is.na(df3$NFC)==FALSE),]

x <- df3$NFC
y <- as.numeric(df3$InCS)

m1 <- multinom(y ~ x)
# summary(m1)
newdata <- data.frame(x = seq(min(x), max(x), length.out = 100))
p1 <- predict(m1, newdata, type = "class")
p2 <- predict(m1, newdata, type = "probs")


logit_plot <- cbind.data.frame(newdata,p2)

logit_plot <- `colnames<-`(logit_plot, c("x","one_l","two_l","three_l"))
logit_plot <- melt(logit_plot, id="x")

```


```{r tabggplotlogit1, fig.cap="Study 1: Probability of selecting each response to the critical slide depending on Need for Cognition", include=FALSE}


ggplot(logit_plot,
       aes(x=x, y=value,
           #color=factor(variable,labels=c("dumb","reason","nothing"))
           linetype=factor(variable,labels=c("dumb","reason","nothing"))
           )) +
  geom_line()+
  xlab("Need for Cognition") + ylab("Predicted Probability") +
  scale_y_continuous(limits = c(0, 1)) + 
  #scale_color_discrete(name="Response to \nCritical Slide", labels=c("Dumbfounded","Nothing Wrong","Reasons"))+
  scale_linetype_discrete(name="Response to \nCritical Slide", labels=c("Dumbfounded","Nothing Wrong","Reasons"))+
  theme_bw() +
  theme(plot.title=element_text(family="Times",
                                size=12
  ),
  legend.text=element_text(family="Times",
                           size=8
  ),
  legend.title=element_text(family="Times",
                            size=10
  ),
  axis.text=element_text(family="Times",
                         colour = "black",
                         size=8
  ),
  axis.ticks.x = element_blank(),
  axis.title=element_text(family="Times",
                          size=12
  ),
  strip.text=element_text(family = "Times",
                          size = 12
  ),
  strip.background = element_rect(fill = "white"),
  legend.position="right")


```



```{r STUDY2}


load("../loaded_data/two.RData")
df3 <- study_2

```



```{r tabs2change in judgement}


##### Study 2 #####

# create variables for reporting t.tests
t <- t.test(df3$InJu1,df3$InJu2, paired = TRUE)

#chisquare test function

custom_chi <- function(x,y){
  a <- length(x)
  b <- length(y)
  c <- rep(1, a)
  d <- rep(2, b)
  e <- c(c,d)
  f <- c(x, y)
  
  g <- data.frame(e,f)
  h <- table(g$e,g$f)
  suppressWarnings(chisq.test(h))
}

c <- suppressWarnings(custom_chi(df3$InJu1,df3$InJu2))

changed_num <- function(x, judgement_1, judgement_2){
  b <- b <- x[which(x$Ju1_bin==judgement_1 & x$Ju2_bin==judgement_2),]
  length(b$Ju1_bin)
  
}

tot_changed_num <- function(x, query){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  if(query == "table")
    print(c)
  if(query == "total") print(length(c$initial_judgement))}


tot_changed_table <- function(x){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  }

change_table <- tot_changed_table(df3)
change_table <- table(change_table)
change_table <- as.data.frame(change_table)
change_table <- change_table[which(change_table$Freq!=0),]
change_table <- change_table[order(change_table$Initial.Judgment, change_table$Revised.Judgment), ]
colnames(change_table) <- c("Initial Judgment","Revised Judgment", "Total Changed")
#order(change_table$Initial.Judgment)
```



```{r tabS2change,results = 'asis', include=TRUE}


apa_table(
   change_table
   , align = c("c", "c")
   , caption = "Study 2 – Changes in Jugment"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```




```{r}

df3$InCS <- df3$InCS

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
#`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

test_condition <- test
  


test <- as.data.frame.matrix((table(df3$InCS,df3$engaged)))
#`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc_eng(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

test_engaged <- test
  
test <- rbind.data.frame(test_condition,test_engaged)
Response <- c("Reasons", "Dumbfounded", "Nothing Wrong"
              ,"Reasons", "Dumbfounded", "Nothing Wrong")
Measure <- c("Manipulation Only","","","Engagement","","")

test <- cbind.data.frame(Measure, Response, test)

test <- `rownames<-`(test, NULL)

makespanners <- function(){
  cog_load <- c(3,4)
  control <- c(5,6)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)




```


```{r tabS2tab1dumb1all,results = 'asis', include=TRUE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c", "c")
   , caption = "Study 2 – Response to the critical slide depending on cognitive load/engagement"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```




```{r STUDY3}


load("../loaded_data/three.RData")
df3 <- study_3
df3 <- df3[which(df3$engaged==T),]

```



```{r tabs3change in judgement}


##### Study 3 #####

# create variables for reporting t.tests
t <- t.test(df3$InJu1,df3$InJu2, paired = TRUE)

#chisquare test function

custom_chi <- function(x,y){
  a <- length(x)
  b <- length(y)
  c <- rep(1, a)
  d <- rep(2, b)
  e <- c(c,d)
  f <- c(x, y)
  
  g <- data.frame(e,f)
  h <- table(g$e,g$f)
  suppressWarnings(chisq.test(h))
}

c <- suppressWarnings(custom_chi(df3$InJu1,df3$InJu2))

changed_num <- function(x, judgement_1, judgement_2){
  b <- b <- x[which(x$Ju1_bin==judgement_1 & x$Ju2_bin==judgement_2),]
  length(b$Ju1_bin)
  
}

tot_changed_num <- function(x, query){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  if(query == "table")
    print(c)
  if(query == "total") print(length(c$initial_judgement))}


tot_changed_table <- function(x){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  }

change_table <- tot_changed_table(df3)
change_table <- table(change_table)
change_table <- as.data.frame(change_table)
change_table <- change_table[which(change_table$Freq!=0),]
change_table <- change_table[order(change_table$Initial.Judgment, change_table$Revised.Judgment), ]
colnames(change_table) <- c("Initial Judgment","Revised Judgment", "Total Changed")
#order(change_table$Initial.Judgment)
```



```{r tabS3change,results = 'asis', include=TRUE}


apa_table(
   change_table
   , align = c("c", "c")
   , caption = "Study 3 – Changes in Jugment"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```




```{r}

df3$InCS <- df3$InCS

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
#`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

test_condition <- test

makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)




```


```{r tabS3tab1dumb1all,results = 'asis', include=TRUE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c", "c")
   , caption = "Study 3 – Response to the critical slide depending on cognitive load/engagement"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```



```{r STUDY4}


load("../loaded_data/four.RData")
df3 <- study_4
df3 <- df3[which(df3$engaged==T),]

```



```{r tabs4change in judgement}


##### Study 4 #####

# create variables for reporting t.tests
t <- t.test(df3$InJu1,df3$InJu2, paired = TRUE)

#chisquare test function

custom_chi <- function(x,y){
  a <- length(x)
  b <- length(y)
  c <- rep(1, a)
  d <- rep(2, b)
  e <- c(c,d)
  f <- c(x, y)
  
  g <- data.frame(e,f)
  h <- table(g$e,g$f)
  suppressWarnings(chisq.test(h))
}

c <- suppressWarnings(custom_chi(df3$InJu1,df3$InJu2))

changed_num <- function(x, judgement_1, judgement_2){
  b <- b <- x[which(x$Ju1_bin==judgement_1 & x$Ju2_bin==judgement_2),]
  length(b$Ju1_bin)
  
}

tot_changed_num <- function(x, query){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  if(query == "table")
    print(c)
  if(query == "total") print(length(c$initial_judgement))}


tot_changed_table <- function(x){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  }

change_table <- tot_changed_table(df3)
change_table <- table(change_table)
change_table <- as.data.frame(change_table)
change_table <- change_table[which(change_table$Freq!=0),]
change_table <- change_table[order(change_table$Initial.Judgment, change_table$Revised.Judgment), ]
colnames(change_table) <- c("Initial Judgment","Revised Judgment", "Total Changed")
#order(change_table$Initial.Judgment)
```



```{r tabS4change,results = 'asis', include=TRUE}


apa_table(
   change_table
   , align = c("c", "c")
   , caption = "Study 4 – Changes in Jugment"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```




```{r}

df3$InCS <- df3$InCS

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
#`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

test_condition <- test

makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)




```


```{r tabS4tab1dumb1all,results = 'asis', include=TRUE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c", "c")
   , caption = "Study 4 – Response to the critical slide depending on cognitive load/engagement"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```




```{r STUDY5}


load("../loaded_data/five.RData")
df3 <- study_5
#df3 <- df3[which(df3$engaged==T),]

```



```{r tabs5change in judgement}


##### Study 5 #####

# create variables for reporting t.tests
t <- t.test(df3$InJu1,df3$InJu2, paired = TRUE)

#chisquare test function

custom_chi <- function(x,y){
  a <- length(x)
  b <- length(y)
  c <- rep(1, a)
  d <- rep(2, b)
  e <- c(c,d)
  f <- c(x, y)
  
  g <- data.frame(e,f)
  h <- table(g$e,g$f)
  suppressWarnings(chisq.test(h))
}

c <- suppressWarnings(custom_chi(df3$InJu1,df3$InJu2))

changed_num <- function(x, judgement_1, judgement_2){
  b <- b <- x[which(x$Ju1_bin==judgement_1 & x$Ju2_bin==judgement_2),]
  length(b$Ju1_bin)
  
}

tot_changed_num <- function(x, query){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  if(query == "table")
    print(c)
  if(query == "total") print(length(c$initial_judgement))}


tot_changed_table <- function(x){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
  }

change_table <- tot_changed_table(df3)
change_table <- table(change_table)
change_table <- as.data.frame(change_table)
change_table <- change_table[which(change_table$Freq!=0),]
change_table <- change_table[order(change_table$Initial.Judgment, change_table$Revised.Judgment), ]
colnames(change_table) <- c("Initial Judgment","Revised Judgment", "Total Changed")
#order(change_table$Initial.Judgment)
```



```{r tabS5change,results = 'asis', include=TRUE}


apa_table(
   change_table
   , align = c("c", "c")
   , caption = "Study 5 – Changes in Jugment"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```




```{r}

df3$InCS <- df3$InCS

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
#`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

test_condition <- test

makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)




```


```{r tabS5tab1dumb1all,results = 'asis', include=TRUE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c", "c")
   , caption = "Study 5 – Response to the critical slide depending on cognitive load/engagement"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```



```{r tab_STUDY_6_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
# knitr::opts_chunk$set(eval = TRUE, echo = TRUE)
#knitr::opts_chunk$set(include = FALSE)
```



```{r tabS6load_libraries_cogload}

##### Study 6 #####
rm(list = ls())
library(citr)
#install.packages("sjstats")
library(plyr)
library(foreign)
library(car)
library(desnum)
library(ggplot2)
library(extrafont)
#devtools::install_github("crsh/papaja")
library(papaja)
#library("dplyr")
library("afex")
library("tibble")
library(scales)
#install.packages("metap")
library(metap)
library(pwr)
library(lsr)
#install.packages("sjstats")
library(sjstats)
library(DescTools)
#inatall.packages("ggstatsplot")
#library(ggstatsplot)
library(VGAM)
library(nnet)
library(mlogit)
library(reshape2)
#install.packages("powerMediation")
library("powerMediation")


#source("load_all_data.R")

#devtools::install_github("benmarwick/wordcountaddin")
#library(wordcountaddin)
#wordcountaddin::text_stats("cogload_1to5_25Sept19.Rmd")
getwd()
```



```{r tabS6loaddatasetStudy6}
#source("~/Dropbox/College/research/Research_general/cog_load/moral_dumbfounding_and_cognitive_load/read_and_sort_raw_data.R")
#source("~/Dropbox/College/research/Research_general/cog_load/moral_dumbfounding_and_cognitive_load/load_study6_data.R")
rm(list = ls())

load("../loaded_data/six.RData")
df3 <- study_6
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]

df4 <- df3[which(df3$condition=="cog_load"),]
df5 <- df3[which(df3$condition=="control"),]
#df3$InCS <- df3$CS

```




```{r}

x <- study_6
x$attention_check1
x$attention_check2
sum(x$attention_check1!=8)#/4

x$attention_check2!=2|x$attention_check2!=5

sum((x$attention_check2==1|x$attention_check2==4)==FALSE)#/4

x$attention_check1[which((x$attention_check2==1|x$attention_check2==4)==FALSE)]

x$attention_check1[which((x$attention_check2==1|x$attention_check2==4)==FALSE&x$attention_check1!=8)]


att1 <- sum(x$attention_check1!=8,na.rm = T)#/4
att2 <- sum((x$attention_check2==1|x$attention_check2==8)==FALSE,na.rm = T)#/4
att_both <- sum((x$attention_check2==1|x$attention_check2==4)==FALSE&x$attention_check1!=8,na.rm = T)#/4


```


```{r}
x <- study_6

x <- x[which(((x$attention_check2==1|x$attention_check2==5)==FALSE&x$attention_check1!=8)==FALSE),]


table(x$condition)
table(x$InJu1)
sum(is.na(x$InJu1))
table(x$InJu2)
sum(is.na(x$InJu2))
table(x$condition)

x <- x[which(x$InJu1!="null"),]
x <- x[which(is.na(x$InJu1)==FALSE),]
x <- x[which(x$InJu2!="null"),]
x <- x[which(is.na(x$InJu2)==FALSE),]
x <- x[which(is.na(x$InCS)==FALSE),]
x <- x[which(x$InCS!="null"),]



study_6_clean <- x
df3 <- study_6_clean
```


```{r tabS6checkingchanges6a, include=FALSE}

length(df3$gender)
table(df3$condition)
table(df3$country)
table(df3$condition,df3$scenario)


```






```{r tabS6change in judgement}

# create variables for reporting t.tests
#t <- t.test(df3$InJu1,df3$InJu2, paired = TRUE)

#chisquare test function

custom_chi <- function(x,y){
  a <- length(x)
  b <- length(y)
  c <- rep(1, a)
  d <- rep(2, b)
  e <- c(c,d)
  f <- c(x, y)
  
  g <- data.frame(e,f)
  h <- table(g$e,g$f)
  suppressWarnings(chisq.test(h))
}

c <- suppressWarnings(custom_chi(df3$InJu1,df3$InJu2))

changed_num <- function(x, judgement_1, judgement_2){
  b <- b <- x[which(x$Ju1_bin==judgement_1 & x$Ju2_bin==judgement_2),]
  length(b$Ju1_bin)
  
}

tot_changed_num <- function(x, query){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("initial_judgement","revised_judgement")
  
  c
  if(query == "table") print(c)
  if(query == "total") print(length(c$initial_judgement))}



tot_changed_table <- function(x){
  
  c <- cbind.data.frame(x$Ju1_bin[which(x$Ju1_bin!=x$Ju2_bin)],x$Ju2_bin[which(x$Ju1_bin!=x$Ju2_bin)])
  colnames(c) <- c("Initial Judgment","Revised Judgment")
  
  c
}

make_change_table <- function(z){
  change_table <- tot_changed_table(z)
  change_table <- table(change_table)
  change_table <- as.data.frame(change_table)
  change_table <- change_table[which(change_table$Freq!=0),]
  change_table <- change_table[order(change_table$Initial.Judgment, change_table$Revised.Judgment), ]
  change_table <- `rownames<-`(change_table,NULL)
  colnames(change_table) <- c("Initial Judgment","Revised Judgment", "Total Changed")
  change_table}


df3 <- study_6_clean
change_table <- make_change_table(df3)

```


```{r tabS6change,results = 'asis', include=TRUE}


apa_table(
   change_table
   , align = c("c","c", "c")
   , caption = "Study 6 – Changes in Jugment (full sample)"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Incest"),]
x <- make_change_table(df3)
Scenario <- c("Julie and Mark", rep("", (length(x$`Initial Judgment`)-1)))
incest <- cbind.data.frame(Scenario,x)

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Jennifer"),]
x <- make_change_table(df3)
Scenario <- c("Jennifer", rep("", (length(x$`Initial Judgment`)-1)))
jennifer <- cbind.data.frame(Scenario,x)

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Trolley"),]
x <- make_change_table(df3)
Scenario <- c("Trolley", rep("", (length(x$`Initial Judgment`)-1)))
trolley <- cbind.data.frame(Scenario,x)

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Heinz"),]
x <- make_change_table(df3)
Scenario <- c("Heinz", rep("", (length(x$`Initial Judgment`)-1)))
heinz <- cbind.data.frame(Scenario,x)

change_table <- rbind.data.frame(incest,jennifer,trolley,heinz)


```



```{r tabS6changeeachscenario,results = 'asis', include=TRUE}


apa_table(
   change_table
   , align = c("l", "c", "c", "c")
   , caption = "Study 6 – Changes in Jugment for each Scenario"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```



```{r tabS6checkingchanges6, include=FALSE}
chisq.test(table(df3$InCS,df3$condition),correct = TRUE)
```


```{r}

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")
  
makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)



```



```{r tabS6tab1dumb1all,results = 'asis', include=TRUE}


apa_table(
   test
   , align = c("l", "c", "c", "c", "c")
   , caption = "Study 6 – Response to the critical slide depending on cognitive load (full sample)"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```



```{r}


y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")

z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
test


#y <- table(df3$condition,df3$Dumb_incl_string)
#y <- as.data.frame(y)
#colnames(y) <- c("condition","InCS","Freq")

# z <- as.data.frame(table(df3$condition,df3$Dumb_incl_string)/length(df3$gender)*2)
# perc <- z$Freq
# test <- cbind(y,perc)
# test$condition
# test


ab_graph <- function(){
  a <- df3[which(df3$condition==levels(as.factor(df3$condition))[1]),]
  b <- df3[which(df3$condition==levels(as.factor(df3$condition))[2]),]
  a#levels(as.factor(df3$condition))[1]
  
  ay <- as.data.frame(table(a$InCS,as.character(a$condition)))
  by <- as.data.frame(table(b$InCS,as.character(b$condition)))
  
  aperc <- ay$Freq/length(a$gender)
  ay <- cbind(ay,aperc)
  colnames(ay) <- c("InCS","condition","Freq","perc")
  
  bperc <- by$Freq/length(b$gender)
  by <- cbind(by,bperc)
  colnames(by) <- c("InCS","condition","Freq","perc")
  
  c <- rbind(ay,by)
  
  c
}

test <- ab_graph()



rm(y)
```


```{r tabS6ch5S6fig1criticalconditionb, fig.cap="Study 6: Responses to critical slide depending on cognitive load", include=FALSE}

#g <- 
ggplot(test, aes(x=InCS, y=perc, fill=factor(condition,labels=c("Cognitive load","Control")))) +
  scale_y_continuous(limits = c(-.03,1),
                     labels = percent_format()
  )+ 
  geom_col(position = "dodge",
           color="black",
           size=.2
  )+
  geom_text(#family = "Times",
            size=4.2,
            aes( label = scales::percent(perc, accuracy = 1),
                 y= perc ),
            stat= "identity",
            vjust = -.5,
            position = position_dodge(.9),
            fontface='plain'
            )+
  geom_text(#family = "Times", 
            size=4.2,
            aes(label = format(Freq),
                y= -3*(..count../100)/(..count..)),
            stat= "count",
            position = position_dodge(0.9),
            #vjust = -.05,
            fontface='plain'
            ) +
  xlab("Response to Critical Slide") +
  ylab("Percentage of participants selecting each response")+
  scale_x_discrete(labels=c("Reasons", "Dumbfounded","Nothing Wrong")) +
  scale_fill_grey(start = .5, end = .8) +
  labs(fill="Condition") +
  #theme_apa() +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(size = .2),
        strip.background  = element_blank(),
        panel.grid = element_blank(),
        plot.title=element_text(#family="Times",
                                size=12
                                ),
        legend.text=element_text(#family="Times",
                                 size=8
                                 ),
        legend.title=element_text(#family="Times",
                                    size=10
                                 ),
        axis.text=element_text(#family="Times",
                                 colour = "black",
                                 size=8
                                 ),
        axis.ticks.x = element_blank(),
        axis.title=element_text(#family="Times",
                                  size=12
                                  ),
        strip.text=element_text(#family = "Times",
                                  size = 12
                                  ),
        #strip.background = element_rect(fill = "white"),
        legend.position="right")





```


```{r}
#suppressWarnings(print(g))
```


```{r}

df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Incest"),]
y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")
z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
incest <- test


df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Jennifer"),]
y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")
z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
cannibal <- test


df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Trolley"),]
y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")
z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
trolley <- test


df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Heinz"),]
y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")
z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
heinz <- test

test <- rbind.data.frame(incest, cannibal, trolley, heinz)

#y <- table(df3$condition,df3$Dumb_incl_string)
#y <- as.data.frame(y)
#colnames(y) <- c("condition","InCS","Freq")

# z <- as.data.frame(table(df3$condition,df3$Dumb_incl_string)/length(df3$gender)*2)
# perc <- z$Freq
# test <- cbind(y,perc)
# test$condition
# test


ab_graph <- function(){
  a <- df3[which(df3$condition==levels(as.factor(df3$condition))[1]),]
  b <- df3[which(df3$condition==levels(as.factor(df3$condition))[2]),]
  a#levels(as.factor(df3$condition))[1]
  
  ay <- as.data.frame(table(a$InCS,as.character(a$condition)))
  by <- as.data.frame(table(b$InCS,as.character(b$condition)))
  
  aperc <- ay$Freq/length(a$gender)
  ay <- cbind(ay,aperc)
  colnames(ay) <- c("InCS","condition","Freq","perc")
  
  bperc <- by$Freq/length(b$gender)
  by <- cbind(by,bperc)
  colnames(by) <- c("InCS","condition","Freq","perc")
  
  c <- rbind(ay,by)
  
  c
}

df3 <- study_6_clean
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Incest"),]
test1 <- ab_graph()
test1$scenario <- rep("Julie and Mark",length(test1$InCS))
incest <- test1

df3 <- study_6_clean
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Jennifer"),]
test1 <- ab_graph()
test1$scenario <- rep("Jennifer",length(test1$InCS))
cannibal <- test1

df3 <- study_6_clean
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Trolley"),]
test1 <- ab_graph()
test1$scenario <- rep("Trolley",length(test1$InCS))
trolley <- test1

df3 <- study_6_clean
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]
df3 <- df3[which(df3$scenario=="Heinz"),]
test1 <- ab_graph()
test1$scenario <- rep("Heinz",length(test1$InCS))
heinz <- test1

df3 <- study_6_clean
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]

test <- rbind.data.frame(incest, cannibal, trolley, heinz)


rm(y)
```




```{r tabS6ch5S6fig2criticalconditionb, fig.cap="Study 6: Responses to critical slide and for the experimental group and the control group for each scenario", include=FALSE}

#g <- 
ggplot(test, aes(x=InCS, y=perc, fill=factor(condition
                                             ,labels=c("Cognitive load","Control")
                                             ))) +
  facet_wrap(~scenario,scales='free')+
  scale_y_continuous(limits = c(-.05,1),
                     labels = percent_format()
  )+ 
  geom_col(position = "dodge",
           color="black",
           size=.2
  )+
  geom_text(#family = "Times",
            size=2.5,
            aes( label = scales::percent(perc,accuracy = 1),
                 y= perc-.005
                 #, color=factor(scenario)
                 ),
            stat= "identity",
            vjust = -.5,
            position = position_dodge(.9),
            fontface='plain'
            )+
  geom_text(#family = "Times", 
            size=2.5,
            aes(label = format(Freq),
                y= -4.5*(..count../100)/(..count..)
                #, color=factor(scenario)
                ),
            stat= "count",
            position = position_dodge(0.9),
            #vjust = -.05,
            fontface='plain'
            ) +
  xlab("Response to Critical Slide") +
  ylab("Percentage of participants selecting each response")+
  scale_x_discrete(labels=c("Reasons", "Dumbfounded","Nothing Wrong")) +
  scale_fill_grey(start = .5, end = .8) +
  labs(fill="Condition") +
  # 
  # geom_text(#family = "Times", 
  #           size=4.2,
  #           aes( label = scales::percent(test$perc),
  #                y= test$perc ),
  #           stat= "identity",
  #           vjust = -.5,
  #           position = position_dodge(.9),
  #           fontface='plain'
  #           )+
  #theme_apa() +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(size = .2),
        strip.background  = element_blank(),
        panel.grid = element_blank(),
        plot.title=element_text(#family="Times",
                                size=8
                                ),
        legend.text=element_text(#family="Times",
                                 size=6
                                 ),
        legend.title=element_text(#family="Times",
                                    size=8
                                    ),
        axis.text=element_text(#family="Times",
                               colour = "black",
                               size=6
                               ),
        axis.ticks.x = element_blank(),
        axis.title=element_text(#family="Times",
                                size=8
                                ),
        strip.text=element_text(#family = "Times",
                                  size = 8
                                  ),
        #  strip.background = element_rect(fill = "white"),
        legend.position="right")





```

```{r}
#suppressWarnings(print(g))
```


```{r tabS6preptableS6}
c <- chisq.test(table(df3$InCS,df3$condition))
rownames(rbind(c$observed,c$expected,c$stdres))



ps <- function(y){
  if(as.numeric(sqrt( y*y) ) >3.3) print(paste0(y,"**"), quote = FALSE)
  else if(as.numeric(sqrt( y*y) ) >1.96) print(paste0(y,"*"), quote = FALSE)
  else print(y)}


x <- c$stdres
x <- round(x, digits = 2)

lapply(x, ps)

#c$stdres <- round(c$stdres,digits=3)
#c$stdres <- ps(c$stdres)

ps(x[1])
ps(x[2])
ps(x[3])

x <- `colnames<-`(
  cbind.data.frame(c(ps(x[1]),ps(x[2]),ps(x[3])),
                   c(ps(x[4]),ps(x[5]),ps(x[6]))),
  c("cog_load","control")
)

rownames(x) <- row.names(c$observed)  

y <- rbind(round(c$observed), round(c$expected, digits = 2))

c(c$stdres[1])


res <- cbind(c("Observed count","","","Expected count","","","Standardised residuals","",""),
      c("Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong"),
      rbind(y,x)
      
      )

row.names(res) <- NULL
colnames(res) <- c("","","Cognitive Load","Control")




```



```{r tabS6tab1dumb,results = 'asis', include=FALSE}


apa_table(
   res
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on cognitive load (full sample)"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   , note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}


#### Incest ####

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Incest"),]

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }

test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")
Response <- c("Reasons","Dumbfounded","Nothing Wrong")
Scenario <- c("Julie and Mark","","")
test <- cbind.data.frame(Scenario,Response,test)
test <- `rownames<-`(test, NULL)

test_incest <- test

#### Jennifer ####

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Jennifer"),]

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }

test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")
Response <- c("Reasons","Dumbfounded","Nothing Wrong")
Scenario <- c("Jennifer","","")
test <- cbind.data.frame(Scenario,Response,test)
test <- `rownames<-`(test, NULL)

test_jennifer <- test

#### Trolley ####

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Trolley"),]

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }

test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")
Response <- c("Reasons","Dumbfounded","Nothing Wrong")
Scenario <- c("Trolley","","")
test <- cbind.data.frame(Scenario,Response,test)
test <- `rownames<-`(test, NULL)

test_trolley <- test

#### Heinz ####

df3 <- study_6_clean
df3 <- df3[which(df3$scenario=="Heinz"),]

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }

test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")
Response <- c("Reasons","Dumbfounded","Nothing Wrong")
Scenario <- c("Heinz","","")
test <- cbind.data.frame(Scenario,Response,test)
test <- `rownames<-`(test, NULL)

test_heinz <- test

test <- rbind(test_incest, test_jennifer, test_trolley, test_heinz)


makespanners <- function(){
  cog_load <- c(3,4)
  control <- c(5,6)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

```



```{r tabS6tab1dumb1allIncest,results = 'asis', include=TRUE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c", "c")
   , caption = "Study 6 – Response to the critical slide depending on cognitive load, for each scenario"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}


y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")

z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
test


#y <- table(df3$condition,df3$Dumb_incl_string)
#y <- as.data.frame(y)
#colnames(y) <- c("condition","InCS","Freq")

# z <- as.data.frame(table(df3$condition,df3$Dumb_incl_string)/length(df3$gender)*2)
# perc <- z$Freq
# test <- cbind(y,perc)
# test$condition
# test


ab_graph <- function(){
  a <- df3[which(df3$condition==levels(as.factor(df3$condition))[1]),]
  b <- df3[which(df3$condition==levels(as.factor(df3$condition))[2]),]
  a#levels(as.factor(df3$condition))[1]
  
  ay <- as.data.frame(table(a$InCS,as.character(a$condition)))
  by <- as.data.frame(table(b$InCS,as.character(b$condition)))
  
  aperc <- ay$Freq/length(a$gender)
  ay <- cbind(ay,aperc)
  colnames(ay) <- c("InCS","condition","Freq","perc")
  
  bperc <- by$Freq/length(b$gender)
  by <- cbind(by,bperc)
  colnames(by) <- c("InCS","condition","Freq","perc")
  
  c <- rbind(ay,by)
  
  c
}

test <- ab_graph()



rm(y)
```


```{r tabS6ch5S6fig2criticalconditionbIncest, fig.cap="Study 6: Responses to critical slide depending on cognitive load (Julie and Mark)", include=FALSE}

ggplot(test, aes(x=InCS, y=perc, fill=factor(condition,labels=c("Cognitive load","Control")))) +
  scale_y_continuous(limits = c(-.03,1),
                     labels = percent_format()
  )+ 
  geom_col(position = "dodge",
           color="black",
           size=.2
  )+
  geom_text(#family = "Times",
    size=4.2,
    aes( label = scales::percent(perc, accuracy = 1),
         y= perc ),
    stat= "identity",
    vjust = -.5,
    position = position_dodge(.9),
    fontface='plain'
  )+
  geom_text(#family = "Times", 
    size=4.2,
    aes(label = format(Freq),
        y= -3*(..count../100)/(..count..)),
    stat= "count",
    position = position_dodge(0.9),
    #vjust = -.05,
    fontface='plain'
  ) +
  xlab("Response to Critical Slide") +
  ylab("Percentage of participants selecting each response")+
  scale_x_discrete(labels=c("Reasons", "Dumbfounded","Nothing Wrong")) +
  scale_fill_grey(start = .5, end = .8) +
  labs(fill="Condition") +
  #theme_apa() +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(size = .2),
        strip.background  = element_blank(),
        panel.grid = element_blank(),
        plot.title=element_text(#family="Times",
          size=12
        ),
        legend.text=element_text(#family="Times",
          size=8
        ),
        legend.title=element_text(#family="Times",
          size=10
        ),
        axis.text=element_text(#family="Times",
          colour = "black",
          size=8
        ),
        axis.ticks.x = element_blank(),
        axis.title=element_text(#family="Times",
          size=12
        ),
        strip.text=element_text(#family = "Times",
          size = 12
        ),
        #strip.background = element_rect(fill = "white"),
        legend.position="right")






```


```{r}
df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]

df3 <- df3[which(df3$scenario=="Incest"),]

df4 <- df3[which(df3$condition=="cog_load"),]
df5 <- df3[which(df3$condition=="control"),]

```

```{r tabS6checkingchanges6aIncest, include=FALSE}

length(df3$gender)
table(df3$condition)
#table(df3$condition,df3$scenario)

```


```{r tabS6checkingchanges6Incest, include=FALSE}
chisq.test(table(df3$InCS,df3$condition),correct = TRUE)
```


```{r}

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
  tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

  makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)



```


```{r}
c <- chisq.test(table(df3$InCS,df3$condition))
rownames(rbind(c$observed,c$expected,c$stdres))



ps <- function(y){
  if(as.numeric(sqrt( y*y) ) >3.3) print(paste0(y,"**"), quote = FALSE)
  else if(as.numeric(sqrt( y*y) ) >1.96) print(paste0(y,"*"), quote = FALSE)
  else print(y)}


x <- c$stdres
x <- round(x, digits = 2)

lapply(x, ps)

#c$stdres <- round(c$stdres,digits=3)
#c$stdres <- ps(c$stdres)

ps(x[1])
ps(x[2])
ps(x[3])

x <- `colnames<-`(
  cbind.data.frame(c(ps(x[1]),ps(x[2]),ps(x[3])),
                   c(ps(x[4]),ps(x[5]),ps(x[6]))),
  c("cog_load","control")
)

rownames(x) <- row.names(c$observed)

paste(round(c$observed,digits = 0))
format(round(c$observed), nsmall = 0)

y <- rbind(format(round(c$observed), nsmall = 0), round(c$expected, digits = 2))

c(c$stdres[1])


res <- cbind(c("Observed count","","","Expected count","","","Standardised residuals","",""),
      c("Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong"),
      rbind.data.frame(y,x)
      
      )

row.names(res) <- NULL
colnames(res) <- c("","","Cognitive Load","Control")




```



```{r tabS6tab1dumbIncest,results = 'asis', include=TRUE}


apa_table(
   res
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on cognitive load (Julie and Mark)"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   , note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```



```{r}
df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]

df3 <- df3[which(df3$scenario=="Jennifer"),]

df4 <- df3[which(df3$condition=="cog_load"),]
df5 <- df3[which(df3$condition=="control"),]

```

```{r tabS6checkingchanges6aJennifer, include=FALSE}

length(df3$gender)
table(df3$condition)
#table(df3$condition,df3$scenario)

```


```{r tabS6checkingchanges6Jennifer, include=FALSE}
chisq.test(table(df3$InCS,df3$condition),correct = TRUE)
```


```{r}

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
  tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

  makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)



```


```{r tabS6tab1dumb1allJennifer,results = 'asis', include=FALSE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Response to the critical slide depending on cognitive load (Jennifer)"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}


y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")

z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
test


#y <- table(df3$condition,df3$Dumb_incl_string)
#y <- as.data.frame(y)
#colnames(y) <- c("condition","InCS","Freq")

# z <- as.data.frame(table(df3$condition,df3$Dumb_incl_string)/length(df3$gender)*2)
# perc <- z$Freq
# test <- cbind(y,perc)
# test$condition
# test


ab_graph <- function(){
  a <- df3[which(df3$condition==levels(as.factor(df3$condition))[1]),]
  b <- df3[which(df3$condition==levels(as.factor(df3$condition))[2]),]
  a#levels(as.factor(df3$condition))[1]
  
  ay <- as.data.frame(table(a$InCS,as.character(a$condition)))
  by <- as.data.frame(table(b$InCS,as.character(b$condition)))
  
  aperc <- ay$Freq/length(a$gender)
  ay <- cbind(ay,aperc)
  colnames(ay) <- c("InCS","condition","Freq","perc")
  
  bperc <- by$Freq/length(b$gender)
  by <- cbind(by,bperc)
  colnames(by) <- c("InCS","condition","Freq","perc")
  
  c <- rbind(ay,by)
  
  c
}

test <- ab_graph()



rm(y)
```


```{r tabS6ch5S6fig2criticalconditionbJennifer, fig.cap="Study 6: Responses to critical slide depending on cognitive load (Jennifer)", include=FALSE}


ggplot(test, aes(x=InCS, y=perc, fill=factor(condition,labels=c("Cognitive load","Control")))) +
  scale_y_continuous(limits = c(-.03,1),
                     labels = percent_format()
  )+ 
  geom_col(position = "dodge",
           color="black",
           size=.2
  )+
  geom_text(#family = "Times",
    size=4.2,
    aes( label = scales::percent(perc, accuracy = 1),
         y= perc ),
    stat= "identity",
    vjust = -.5,
    position = position_dodge(.9),
    fontface='plain'
  )+
  geom_text(#family = "Times", 
    size=4.2,
    aes(label = format(Freq),
        y= -3*(..count../100)/(..count..)),
    stat= "count",
    position = position_dodge(0.9),
    #vjust = -.05,
    fontface='plain'
  ) +
  xlab("Response to Critical Slide") +
  ylab("Percentage of participants selecting each response")+
  scale_x_discrete(labels=c("Reasons", "Dumbfounded","Nothing Wrong")) +
  scale_fill_grey(start = .5, end = .8) +
  labs(fill="Condition") +
  #theme_apa() +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(size = .2),
        strip.background  = element_blank(),
        panel.grid = element_blank(),
        plot.title=element_text(#family="Times",
          size=12
        ),
        legend.text=element_text(#family="Times",
          size=8
        ),
        legend.title=element_text(#family="Times",
          size=10
        ),
        axis.text=element_text(#family="Times",
          colour = "black",
          size=8
        ),
        axis.ticks.x = element_blank(),
        axis.title=element_text(#family="Times",
          size=12
        ),
        strip.text=element_text(#family = "Times",
          size = 12
        ),
        #strip.background = element_rect(fill = "white"),
        legend.position="right")






```



```{r}
c <- chisq.test(table(df3$InCS,df3$condition))
rownames(rbind(c$observed,c$expected,c$stdres))



ps <- function(y){
  if(as.numeric(sqrt( y*y) ) >3.3) print(paste0(y,"**"), quote = FALSE)
  else if(as.numeric(sqrt( y*y) ) >1.96) print(paste0(y,"*"), quote = FALSE)
  else print(y)}


x <- c$stdres
x <- round(x, digits = 2)

lapply(x, ps)

#c$stdres <- round(c$stdres,digits=3)
#c$stdres <- ps(c$stdres)

ps(x[1])
ps(x[2])
ps(x[3])

x <- `colnames<-`(
  cbind.data.frame(c(ps(x[1]),ps(x[2]),ps(x[3])),
                   c(ps(x[4]),ps(x[5]),ps(x[6]))),
  c("cog_load","control")
)

rownames(x) <- row.names(c$observed)  

y <- rbind(round(c$observed), round(c$expected, digits = 2))

c(c$stdres[1])


res <- cbind(c("Observed count","","","Expected count","","","Standardised residuals","",""),
      c("Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong"),
      rbind(y,x)
      
      )

row.names(res) <- NULL
colnames(res) <- c("","","Cognitive Load","Control")




```



```{r tabS6tab1dumbJennifer,results = 'asis', include=TRUE}


apa_table(
   res
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on cognitive load (Jennifer)"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   , note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```



```{r}
df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]

df3 <- df3[which(df3$scenario=="Trolley"),]

df4 <- df3[which(df3$condition=="cog_load"),]
df5 <- df3[which(df3$condition=="control"),]

```

```{r tabS6checkingchanges6aTrolley, include=FALSE}

length(df3$gender)
table(df3$condition)
#table(df3$condition,df3$scenario)

```


```{r tabcheckingchanges6Trolley, include=FALSE}
chisq.test(table(df3$InCS,df3$condition),correct = TRUE)
```


```{r}

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
  tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  

test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")

  makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)



```


```{r tabS6tab1dumb1allTrolley,results = 'asis', include=FALSE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Response to the critical slide depending on cognitive load (Trolley)"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}


y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")

z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
test


#y <- table(df3$condition,df3$Dumb_incl_string)
#y <- as.data.frame(y)
#colnames(y) <- c("condition","InCS","Freq")

# z <- as.data.frame(table(df3$condition,df3$Dumb_incl_string)/length(df3$gender)*2)
# perc <- z$Freq
# test <- cbind(y,perc)
# test$condition
# test


ab_graph <- function(){
  a <- df3[which(df3$condition==levels(as.factor(df3$condition))[1]),]
  b <- df3[which(df3$condition==levels(as.factor(df3$condition))[2]),]
  a#levels(as.factor(df3$condition))[1]
  
  ay <- as.data.frame(table(a$InCS,as.character(a$condition)))
  by <- as.data.frame(table(b$InCS,as.character(b$condition)))
  
  aperc <- ay$Freq/length(a$gender)
  ay <- cbind(ay,aperc)
  colnames(ay) <- c("InCS","condition","Freq","perc")
  
  bperc <- by$Freq/length(b$gender)
  by <- cbind(by,bperc)
  colnames(by) <- c("InCS","condition","Freq","perc")
  
  c <- rbind(ay,by)
  
  c
}

test <- ab_graph()



rm(y)
```


```{r tabS6ch5S6fig2criticalconditionbTrolley, fig.cap="Study 6: Responses to critical slide depending on cognitive load (Trolley)", include=FALSE}


ggplot(test, aes(x=InCS, y=perc, fill=factor(condition,labels=c("Cognitive load","Control")))) +
  scale_y_continuous(limits = c(-.03,1),
                     labels = percent_format()
  )+ 
  geom_col(position = "dodge",
           color="black",
           size=.2
  )+
  geom_text(#family = "Times",
    size=4.2,
    aes( label = scales::percent(perc, accuracy = 1),
         y= perc ),
    stat= "identity",
    vjust = -.5,
    position = position_dodge(.9),
    fontface='plain'
  )+
  geom_text(#family = "Times", 
    size=4.2,
    aes(label = format(Freq),
        y= -3*(..count../100)/(..count..)),
    stat= "count",
    position = position_dodge(0.9),
    #vjust = -.05,
    fontface='plain'
  ) +
  xlab("Response to Critical Slide") +
  ylab("Percentage of participants selecting each response")+
  scale_x_discrete(labels=c("Reasons", "Dumbfounded","Nothing Wrong")) +
  scale_fill_grey(start = .5, end = .8) +
  labs(fill="Condition") +
  #theme_apa() +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(size = .2),
        strip.background  = element_blank(),
        panel.grid = element_blank(),
        plot.title=element_text(#family="Times",
          size=12
        ),
        legend.text=element_text(#family="Times",
          size=8
        ),
        legend.title=element_text(#family="Times",
          size=10
        ),
        axis.text=element_text(#family="Times",
          colour = "black",
          size=8
        ),
        axis.ticks.x = element_blank(),
        axis.title=element_text(#family="Times",
          size=12
        ),
        strip.text=element_text(#family = "Times",
          size = 12
        ),
        #strip.background = element_rect(fill = "white"),
        legend.position="right")






```



```{r}
c <- chisq.test(table(df3$InCS,df3$condition))
rownames(rbind(c$observed,c$expected,c$stdres))



ps <- function(y){
  if(as.numeric(sqrt( y*y) ) >3.3) print(paste0(y,"**"), quote = FALSE)
  else if(as.numeric(sqrt( y*y) ) >1.96) print(paste0(y,"*"), quote = FALSE)
  else print(y)}


x <- c$stdres
x <- round(x, digits = 2)

lapply(x, ps)

#c$stdres <- round(c$stdres,digits=3)
#c$stdres <- ps(c$stdres)

ps(x[1])
ps(x[2])
ps(x[3])

x <- `colnames<-`(
  cbind.data.frame(c(ps(x[1]),ps(x[2]),ps(x[3])),
                   c(ps(x[4]),ps(x[5]),ps(x[6]))),
  c("cog_load","control")
)

rownames(x) <- row.names(c$observed)  

y <- rbind(round(c$observed), round(c$expected, digits = 2))

c(c$stdres[1])


res <- cbind(c("Observed count","","","Expected count","","","Standardised residuals","",""),
      c("Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong"),
      rbind(y,x)
      
      )

row.names(res) <- NULL
colnames(res) <- c("","","Cognitive Load","Control")




```



```{r tabS6tab1dumbTrolley,results = 'asis', include=TRUE}


apa_table(
   res
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on cognitive load (Trolley)"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   , note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```




```{r}
df3 <- study_6_clean
#df3$InCS
df3 <- df3[which(is.na(df3$InCS)==FALSE),]
df3 <- df3[which(df3$InCS!="null"),]

df3 <- df3[which(df3$scenario=="Heinz"),]

df4 <- df3[which(df3$condition=="cog_load"),]
df5 <- df3[which(df3$condition=="control"),]

```

```{r tabS6checkingchanges6aHeinz, include=FALSE}

length(df3$gender)
table(df3$condition)
#table(df3$condition,df3$scenario)

```


```{r tabS6checkingchanges6Heinz, include=FALSE}
chisq.test(table(df3$InCS,df3$condition),correct = TRUE)
```


```{r}

test <- as.data.frame.matrix((table(df3$InCS,df3$condition)))
`rownames<-`(test, c("nothing wrong","no reason","reasons"))
test <- as.matrix((test))
test1 <- cbind(test[,1],test[,2])
test2 <- `colnames<-`(test1, c("cognitive load","control"))

tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
  tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
test <- tb_count_perc(df3)
test <- as.data.frame(test)
colnames(test) <- c("N","\\%","N","\\%")
  
  makespanners <- function(){
  cog_load <- c(2,3)
  control <- c(4,5)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

#test <- tb_count_perc(df3)
#tb_count_perc(df3a)



```


```{r tabS6tab1dumb1allHeinz,results = 'asis', include=FALSE}


apa_table(
   test
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Response to the critical slide depending on cognitive load (Heinz)"
   #, added_stub_head = "Response to critical slide"
   , col_spanners = makespanners()
   #, note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}


y <- table(df3$condition,df3$InCS)
y <- as.data.frame(y)
colnames(y) <- c("condition","InCS","Freq")

z <- as.data.frame(table(df3$condition,df3$InCS)/length(df3$gender)*2)
perc <- z$Freq
test <- cbind(y,perc)
test$condition
test


#y <- table(df3$condition,df3$Dumb_incl_string)
#y <- as.data.frame(y)
#colnames(y) <- c("condition","InCS","Freq")

# z <- as.data.frame(table(df3$condition,df3$Dumb_incl_string)/length(df3$gender)*2)
# perc <- z$Freq
# test <- cbind(y,perc)
# test$condition
# test


ab_graph <- function(){
  a <- df3[which(df3$condition==levels(as.factor(df3$condition))[1]),]
  b <- df3[which(df3$condition==levels(as.factor(df3$condition))[2]),]
  a#levels(as.factor(df3$condition))[1]
  
  ay <- as.data.frame(table(a$InCS,as.character(a$condition)))
  by <- as.data.frame(table(b$InCS,as.character(b$condition)))
  
  aperc <- ay$Freq/length(a$gender)
  ay <- cbind(ay,aperc)
  colnames(ay) <- c("InCS","condition","Freq","perc")
  
  bperc <- by$Freq/length(b$gender)
  by <- cbind(by,bperc)
  colnames(by) <- c("InCS","condition","Freq","perc")
  
  c <- rbind(ay,by)
  
  c
}

test <- ab_graph()



rm(y)
```


```{r tabS6ch5S6fig2criticalconditionbHeinz, fig.cap="Study 6: Responses to critical slide depending on cognitive load (Heinz)", include=FALSE}


ggplot(test, aes(x=InCS, y=perc, fill=factor(condition,labels=c("Cognitive load","Control")))) +
  scale_y_continuous(limits = c(-.03,1),
                     labels = percent_format()
  )+ 
  geom_col(position = "dodge",
           color="black",
           size=.2
  )+
  geom_text(#family = "Times",
    size=4.2,
    aes( label = scales::percent(perc, accuracy = 1),
         y= perc ),
    stat= "identity",
    vjust = -.5,
    position = position_dodge(.9),
    fontface='plain'
  )+
  geom_text(#family = "Times", 
    size=4.2,
    aes(label = format(Freq),
        y= -3*(..count../100)/(..count..)),
    stat= "count",
    position = position_dodge(0.9),
    #vjust = -.05,
    fontface='plain'
  ) +
  xlab("Response to Critical Slide") +
  ylab("Percentage of participants selecting each response")+
  scale_x_discrete(labels=c("Reasons", "Dumbfounded","Nothing Wrong")) +
  scale_fill_grey(start = .5, end = .8) +
  labs(fill="Condition") +
  #theme_apa() +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(size = .2),
        strip.background  = element_blank(),
        panel.grid = element_blank(),
        plot.title=element_text(#family="Times",
          size=12
        ),
        legend.text=element_text(#family="Times",
          size=8
        ),
        legend.title=element_text(#family="Times",
          size=10
        ),
        axis.text=element_text(#family="Times",
          colour = "black",
          size=8
        ),
        axis.ticks.x = element_blank(),
        axis.title=element_text(#family="Times",
          size=12
        ),
        strip.text=element_text(#family = "Times",
          size = 12
        ),
        #strip.background = element_rect(fill = "white"),
        legend.position="right")




```


```{r}
c <- chisq.test(table(df3$InCS,df3$condition))
rownames(rbind(c$observed,c$expected,c$stdres))



ps <- function(y){
  if(as.numeric(sqrt( y*y) ) >3.3) print(paste0(y,"**"), quote = FALSE)
  else if(as.numeric(sqrt( y*y) ) >1.96) print(paste0(y,"*"), quote = FALSE)
  else print(y)}


x <- c$stdres
x <- round(x, digits = 2)

lapply(x, ps)

#c$stdres <- round(c$stdres,digits=3)
#c$stdres <- ps(c$stdres)

ps(x[1])
ps(x[2])
ps(x[3])

x <- `colnames<-`(
  cbind.data.frame(c(ps(x[1]),ps(x[2]),ps(x[3])),
                   c(ps(x[4]),ps(x[5]),ps(x[6]))),
  c("cog_load","control")
)

rownames(x) <- row.names(c$observed)  

y <- rbind(round(c$observed), round(c$expected, digits = 2))

c(c$stdres[1])


res <- cbind(c("Observed count","","","Expected count","","","Standardised residuals","",""),
      c("Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong"),
      rbind(y,x)
      
      )

row.names(res) <- NULL
colnames(res) <- c("","","Cognitive Load","Control")




```



```{r tabS6tab1dumbHeinz,results = 'asis', include=TRUE}


apa_table(
   res
   , align = c("l", "l", "c", "c", "c")
   , caption = "Study 6 – Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on cognitive load (Heinz)"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   , note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


```{r}
library(citr)
#install.packages("sjstats")
library(plyr)
library(foreign)
library(car)
library(desnum)
library(ggplot2)
library(extrafont)
#devtools::install_github("crsh/papaja")
library(papaja)
#library("dplyr")
library("afex")
library("tibble")
library(scales)
#install.packages("metap")
library(metap)
library(pwr)
library(lsr)
#install.packages("sjstats")
library(sjstats)
library(DescTools)
#inatall.packages("ggstatsplot")
#library(ggstatsplot)
library(VGAM)
library(nnet)
library(mlogit)
library(reshape2)
#install.packages("powerMediation")
library("powerMediation")

```


```{r ch5setupcombineddata}

rm(list=ls())
load("../loaded_data/one.RData")
load("../loaded_data/two.RData")
load("../loaded_data/three.RData")
load("../loaded_data/four.RData")
load("../loaded_data/five.RData")
load("../loaded_data/six.RData")
load("../loaded_data/combined.RData")



```


```{r ch5allpreptable}
rbind(table(engaged0_2_3a$InCS,engaged0_2_3a$condition),
      table(engaged0_2_3b$InCS,engaged0_2_3b$condition))


make4table1 <- function(){
  
  tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
}

  
  rows <- c("Reasons","Dumbfounded","Nothing wrong")
  
  t0 <- tb_count_perc(college)
  t1 <- tb_count_perc(one)
  t2 <- tb_count_perc(two)
  t3 <- tb_count_perc(three)
  t5 <- tb_count_perc(study5)
  t6 <- tb_count_perc(df6)
  t23 <- tb_count_perc(two_three)
  t23e7 <- tb_count_perc(engaged0_2_3a)
  t23e8 <- tb_count_perc(engaged0_2_3b)
  t023 <- tb_count_perc(zero_two_three)
  t0123 <- tb_count_perc(zero_one_two_three)
  t01235 <- tb_count_perc(zero_one_two_three_five)
  t012356 <- tb_count_perc(zero_one_two_three_five_six)


  
  c("Study 1"," "," ",
                 "Study 2"," "," ",
                 "Study 3"," "," ",
                 "Study 4"," "," ",
                 "Study 5"," "," ",
                 "Study 6"," "," ",
                 "Studies 3 and 4"," "," ",
                 "Studies 3 and 4 engaged 1"," "," ",
                 "Studies 3 and 4 engaged 2"," "," ",
                 "Studies 1, 3, and 4"," "," ",
                 "Studies 1, 2, 3, and 4"," "," ")
  rbind(t0,t1,t2,t3,t5,t6,t23,t23e7,t23e8,t023,t012356)
  
  rows_left <- c("Study 1"," "," ",
                 "Study 2"," "," ",
                 "Study 3"," "," ",
                 "Study 4"," "," ",
                 "Study 5"," "," ",
                 "Study 6"," "," ",
                 "Studies 3 and 4"," "," ",
                 "Studies 3 and 4 engaged 1"," "," ",
                 "Studies 3 and 4 engaged 2"," "," ",
                 "Studies 1, 3, and 4"," "," ",
                 "Studies 1, 2, 3, and 4"," "," ")
  
  
  test1 <- cbind(c("Study 1*"," "," ",
                       "Study 2"," "," ",
                       "Study 3*"," "," ",
                       "Study 4"," "," ",
                       "Study 5"," "," ",
                       "Study 6"," "," ",    
                       "All Studies*"," "," "),
                     rows,
                     unname(rbind(t0,t1,t2,t3,t5,t6,t012356)))
  
  cols <- c("Study","Response","N","percent","N","percent")
  test1 <- `colnames<-`(test1, cols)
  
  test1
  
}

make4table1()

make4table2 <- function(){
  
  tb_count_perc <- function(x){
  tc <- table(x$InCS,x$condition)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$condition=="cog_load")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$condition=="control")*100),"%"))
  }
  
  tb_count_perc_eng <- function(x){
  tc <- table(x$InCS,x$engaged)
  cbind(tc[,1],paste0(round(tc[,1]/sum(x$engaged=="engaged")*100),"%"),
        tc[,2],paste0(round(tc[,2]/sum(x$engaged=="not engaged")*100),"%"))
  }
  
  one$study <- rep("one",length(one$gender))
  one_e <- cbind.data.frame(one$engaged, one$InCS, one$cog_load_CS_num, one$NFC, one$reason_always, one$changed,one$gender, one$Ju1_bin, one$Ju2_bin,one$right_change, one$study)
colnames(one_e) <- c("condition","InCS","cog_load_CS_num","NFC","reason_always","changed","gender","Ju1_bin","Ju2_bin","right_change", "study")
  one_e$condition <- car::recode(one_e$condition, "'engaged'='cog_load';'not engaged'='control'")
  eng_0123a <- rbind(engaged0_2_3a,one_e,df5,df6)
  eng_0123b <- rbind(engaged0_2_3b,one_e,df5,df6)
  
  rows <- c("Reasons","Dumbfounded","Nothing wrong")
  
  t0 <- tb_count_perc(college)
  t1 <- tb_count_perc_eng(one)
  df3 <- two
  df3 <- df3[which(df3$engaged==TRUE),]
  t2 <- tb_count_perc(df3)
  df3 <- three
  df3 <- df3[which(df3$engaged==TRUE),]
  t3 <- tb_count_perc(df3)
  t5 <- tb_count_perc(study5)
  t6 <- tb_count_perc(df6)
  t0123a <- tb_count_perc(eng_0123a)
  t0123b <- tb_count_perc(eng_0123b)
  t023 <- tb_count_perc(zero_two_three)
  t0123 <- tb_count_perc(zero_one_two_three)
  
  
  
  rbind(t0,t1,t2,t3,t5,t6,t0123a)#,t0123b)
  
  rows_left <- c("Study 1"," "," ",
                 "Study 2"," "," ",
                 "Study 3"," "," ",
                 "Study 4"," "," ",
                 "Study 5"," "," ",
                 "Studies 3 and 4"," "," ",
                 "Studies 3 and 4 engaged 1"," "," ",
                 "Studies 3 and 4 engaged 2"," "," ",
                 "Studies 1, 3, and 4"," "," ",
                 "Studies 1, 2, 3, and 4"," "," ")
  
  
  test1 <- cbind(c("Study 1*"," "," ",
                 "Study 2 (engaged)*"," "," ",
                 "Study 3 (engaged)**"," "," ",
                 "Study 4 (engaged)"," "," ",
                 "Study 5"," "," ",
                 "Study 6"," "," ",
                 "All studies (engaged)**"," "," "#,
                 #"All studies (engaged b)**"," "," "
                 ),
                 rows,
                     unname(rbind(t0,t1,t2,t3,t5,t6,t0123a
                                  #,t0123b
                                  )))
  
  cols <- c("Study","Response","N","percent","N","percent")
  test1 <- `colnames<-`(test1, cols)
  
  test1
  
}

make4table2()

test1 <- make4table1()
test2 <- make4table2()



makespanners <- function(){
  cog_load <- c(3,4)
  control <- c(5,6)
  spans <- list(cog_load,control)
  names(spans) <- c("Cognitive Load","Control")
  spans
}

rm(make4table1,make4table2)

```

```{r combinednoengagement}
df3 <- zero_one_two_three_five
c <- chisq.test(table(df3$InCS,df3$condition))
w <- sqrt(c[]$statistic/length(df3$gender))
pw <- pwr.chisq.test(w=w,N=length(df3$InCS),df=(3-1),sig.level = .05)


```




```{r ch5taballraw,results = 'asis', include=TRUE}
#setwd("Chapter_3")

apa_table(
   test1
   , align = c("l", "l", "c", "c", "c", "c")
   , caption = "Responses to critical slide for all cognitive load studies (raw)"
   #, added_stub_head = "Response to critical slide"
   , note = "*significant variation at \\emph{p} < .05; **significant variation at \\emph{p} < .001"
   , col_spanners = makespanners()
   , small = TRUE
   , escape = FALSE
   
)

#rm(test1)

```

```{r ch5taballeng,results = 'asis', include=TRUE}
#setwd("Chapter_3")

apa_table(
   test2
   , align = c("l", "l", "c", "c", "c", "c")
   , caption = "Responses to critical slide for all cognitive load studies (controlling for engagement)"
   #, added_stub_head = "Response to critical slide"
   , note = "*significant variation at \\emph{p} < .05; **significant variation at \\emph{p} < .001"
   , col_spanners = makespanners()
   , small = TRUE
   , escape = FALSE
   
)

rm(makespanners,test2)

```

```{r combinedandmeta1}

df3 <- eng_0123a
c <- chisq.test(table(df3$InCS,df3$condition))
w <- sqrt(c[]$statistic/length(df3$gender))
pw <- pwr.chisq.test(w=w,N=length(df3$InCS),df=(3-1),sig.level = .05)




table_values(c(88,83,177),c(63,53,196))


```



```{r preptableSall}

df3 <- eng_0123a

c <- chisq.test(table(df3$InCS,df3$condition))
rownames(rbind(c$observed,c$expected,c$stdres))



ps <- function(y){
  if(as.numeric(sqrt( y*y) ) >3.3) print(paste0(y,"**"), quote = FALSE)
  else if(as.numeric(sqrt( y*y) ) >1.96) print(paste0(y,"*"), quote = FALSE)
  else print(y)}


x <- c$stdres
x <- round(x, digits = 2)

lapply(x, ps)

#c$stdres <- round(c$stdres,digits=3)
#c$stdres <- ps(c$stdres)

ps(x[1])
ps(x[2])
ps(x[3])

x <- `colnames<-`(
  cbind.data.frame(c(ps(x[1]),ps(x[2]),ps(x[3])),
                   c(ps(x[4]),ps(x[5]),ps(x[6]))),
  c("cog_load","control")
)

rownames(x) <- row.names(c$observed)  
c$expected


y <- rbind(round(c$observed), round(c$expected, digits = 2))

c(c$stdres[1])

y
res <- cbind(c("Observed count","","","Expected count","","","Standardised residuals","",""),
      c("Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong",
        "Reasons","Dumbfounded","Nothing Wrong"),
      rbind(y,x)
      
      )

row.names(res) <- NULL
colnames(res) <- c("","","Cognitive Load","Control")




```

```{r Salltab1dumb,results = 'asis', include=FALSE}


apa_table(
   res
   , align = c("l", "l", "c", "c", "c")
   , caption = "Studies 1-6 – Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on cognitive load"
   #, added_stub_head = "Response to critical slide"
   #, col_spanners = makespanners()
   , note = "* = sig. at \\emph{p} < .05; ** = sig. at \\emph{p} < .001"
   , escape = FALSE
   
)

```


