## Heinz/Druggist
* Do you agree that the druggist has to make a living?
* And do you accept that Heinz broke into the druggist's store?
* And do you accept that he stole from him?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;________

* Do think that Heinz should try to save his wife's life?
* And do you agree that he tried to get the money together
* And do you accept that Heinz tried to negotiate with the druggist

## Trolley
* Do you accept that five people would have died if Paul didn't push the man?
* And this man is the only way available to stop the trolley? (Paul does not weigh enough)
* Do you agree that in stopping the trolley Paul saved the lives of five people?

## Cannibal
* The body had been donated for research, it was to be discarded the next day. You must agree then that it had obviously fulfilled its purpose?
* Do you accept that the body was already dead?
* And do you accept that there was no risk of disease?

## Incest
* Do you not agree that any concerns regarding reproductive complications are eased by their using of two forms of contraception?
* And do you accept that they are both consenting adults, and that they both consented and enjoyed it?
* And do you concede that nobody else was affected by their actions?