# Contributions

Contributed to Conception and design: CMH, MMG, ERI, ELK

Contributed to acquisition of data: CMH

Contributed to analysis and interpretation of data: CMH, MMG, ERI, ELK

Drafted and/or revised the article: CMH, MMG, ERI, ELK

Approved the submitted version for publication: CMH, MMG, ERI, ELK

# Funding Information

The Study reported here was funded by University of Limerick, Education and Health Sciences seed funding. Study S5 was funded by Mary Immaculate College seed funding. 

# Data Accessibility Statement
All data and analysis code are publicly available on this project's OSF page at [https://osf.io/fcd5r/?view_only=9fb6e506e53340c189b98453bb2b6eaf](https://osf.io/fcd5r/?view_only=9fb6e506e53340c189b98453bb2b6eaf). Materials are also available including the full text of the jsPsych script.

# Figure Titles

## Main Manuscript

Figure 1: Hypothesized relationship between deliberation and responses in the dumbfounding paradigm

Figure 2: Responses to critical slide depending on cognitive load

Figure 3: Responses to critical slide and for the experimental group and the control group for each scenario

## Supplementary Materials

Figure 1: Screenshot of Attention Check

Figure 2: Screenshot of Attention Check

Figure 3: Study S1: Responses to critical slide and for the experimental group (*N* = 33) and the control group (*N* = 33)

Figure 4: Study S1: Probability of selecting each response to the critical slide depending on Need for Cognition

Figure 5: Sample dot patterns - more simple for the control group (a) and higher complexity for the experimental condition (b)

Figure 6: Study S2: Responses to critical slide for (left) the experimental group (*N* = 51) vs the control group (*N* = 49); and (right) depending on engagement (*N* = 56) or non-engagement (*N* = 44) with the memory task

Figure 7: Study S2: Probability of selecting each response to the critical slide depending on Need for Cognition

Figure 8: Study S3: Responses to critical slide for the cognitive load group (*N* = 68) and the control group (*N* = 61)

Figure 9: Study S3: Probability of selecting each response to the critical slide depending on Need for Cognition

Figure 10: Study S4: Responses to critical slide for the cognitive load group (*N* = 64) and the control group (*N* = 61)

Figure 11: Study S4: Probability of selecting each response to the critical slide depending on Need for Cognition

Figure 12: Study S5: Responses to critical slide and for the experimental group (*N* = 98) and the control group (*N* = 106)

Figure 13: Study S5: Probability of selecting each response to the critical slide depending on Need for Cognition





